version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  hadoop-master:
    hostname: hadoop-master
    build:
      context: .
      dockerfile: Dockerfile
    image: jinlingan/docker-hadoop:2.6.0-cdh5.16.2
    volumes: 
      - ./etc/hadoop/conf/hdfs-site.xml:/etc/hadoop/conf/hdfs-site.xml
      - ./etc/hadoop/conf/yarn-site.xml:/etc/hadoop/conf/yarn-site.xml
      - ./bin/start-yarn.sh:/start-yarn.sh
    ports:
    - 50070:50070
    - 50075:50075
    - 8020:8020
    - 8042:8042
    - 8088:8088
    - 8188:8188
    - 19888:19888
  hadoop-second-master:
    hostname: hadoop-second-master
    build:
      context: .
      dockerfile: Dockerfile
    image: jinlingan/docker-hadoop:2.6.0-cdh5.16.2
    volumes: 
      - ./etc/hadoop/conf/hdfs-site.xml:/etc/hadoop/conf/hdfs-site.xml
      - ./etc/hadoop/conf/yarn-site.xml:/etc/hadoop/conf/yarn-site.xml
    ports: 
      - 50090:50090
    command: ["supervisord", "-c", "/etc/supervisord-secondary.conf", "-n"]
  worker1:
    hostname: worker1
    build:
      context: .
      dockerfile: Dockerfile
    image: jinlingan/docker-hadoop:2.6.0-cdh5.16.2
    volumes: 
      - ./etc/hadoop/conf/hdfs-site.xml:/etc/hadoop/conf/hdfs-site.xml
      - ./etc/hadoop/conf/yarn-site.xml:/etc/hadoop/conf/yarn-site.xml
      - ./in.txt:/tmp/in.txt
    # volumes: 
    #   - ./etc/hadoop/conf/hdfs-site.xml:/etc/hadoop/conf/hdfs-site.xml
    # ports: 
    #   - 50090:50090
    command: ["supervisord", "-c", "/etc/supervisord-slave.conf", "-n"]